export const DOM = {
  list: document.getElementById('chatList'),
  search: document.getElementById('search'),
  input: document.getElementById('input'),
  send: document.getElementById('send'),
  messages: document.getElementById('messages'),
  activeChatTitle: document.getElementById('chat-title'),
  activeChatImage: document.getElementById('chat-image'),
  newChatBtn: document.getElementById('newChatBtn'),
  newChatModal: document.getElementById('newChatModal'),
  chatTitleInput: document.getElementById('chatTitleInput'),
  chatAvatarInput: document.getElementById('chatAvatarInput'),
  chatAvatarPreview: document.getElementById('chatAvatarPreview'),
  createChatCancel: document.getElementById('createChatCancel'),
  createChatSave: document.getElementById('createChatSave'),
  createChatError: document.getElementById('createChatError'),
  profileBtn: document.getElementById('profileBtn'),
  profileAvatar: document.getElementById('profileAvatar'),
  profileModal: document.getElementById('profileModal'),
  profileNameInput: document.getElementById('profileNameInput'),
  profileAvatarInput: document.getElementById('profileAvatarInput'),
  profileAvatarPreview: document.getElementById('profileAvatarPreview'),
  profileEmail: document.getElementById('profileEmail'),
  profileCancel: document.getElementById('profileCancel'),
  profileSave: document.getElementById('profileSave'),
  profileError: document.getElementById('profileError'),
  logoutBtn: document.getElementById('logoutBtn'),
};
